config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/static_pages/index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: :edit
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    delete "/logout", to: "sessions#destroy"

    resources :books, param: :id, only: %i(show new create) do
      resources :reviews
    end

    resources :users do
      resources :like_books, only: :index
      resources :transactions, only: %i(index show destroy)
    end

    resources :books do
      resources :like_books
      resources :transactions
    end

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages
      resources :books do
        collection do
          get :export_excel
        end
      end
      resources :authors
      resources :publishers
      resources :categories
      resources :users do
        member do
          post "active"
        end
      end
      resources :transactions
    end

    resources :authors do
      resources :follows, only: %i(create destroy)
    end

    resources :publishers, only: %i(show index) do
      resources :follows, only: %i(create destroy)
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :reviews, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :books_categories, dependent: :destroy
  has_many :categories, through: :books_categories
  has_many :transactions, dependent: :destroy
  has_many :books_authors, dependent: :destroy
  has_many :authors, through: :books_authors
  has_many :user_like_books, dependent: :destroy
  has_many :users, through: :user_like_books
  delegate :name, to: :publisher, prefix: true, allow_nil: true
  accepts_nested_attributes_for :books_authors, allow_destroy: true
  accepts_nested_attributes_for :books_categories, allow_destroy: true
  accepts_nested_attributes_for :images
  validates :title, presence: true, length: {maximum: Settings.book.title_max}
  validates :published_year, numericality: {only_integer: true,
                                            greater_than_or_equal_to:
                                            Settings.book.year}
  validates :book_amount, numericality: {only_integer: true,
                                         greater_than_or_equal_to:
                                         Settings.book.amount}
  validates :publisher_id, presence: true
  validates :author_ids, presence: {message: I18n.t("admin.book.select")}
  validates :category_ids, presence: {message: I18n.t("admin.book.select")}
  scope :search_all, lambda {|query|
    joins(:publisher, :authors, :categories).where(
      "books.title LIKE :q OR books.description LIKE :q
        OR publishers.name LIKE :q OR authors.name LIKE :q
        OR categories.category_name LIKE :q
        ",
      q: "%#{query}%"
    )
  }
  scope :filtered_by_name, lambda {|name|
    where("name LIKE ?", "%#{name}%") if name.present?
  }

  before_create :set_default_average_rating

  private

  def set_default_average_rating
    self.average_rating ||= 0
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :find_book, except: %i(index new create export_excel)
  before_action :set_books, only: [:index]
  before_action :remove_images_before_update, only: [:update]
  def index
    @books = @books.paginate(page: params[:page],
                             per_page: Settings.page.limit_items)
  end

  def export_excel
    search = session[:search] || ""
    @books = Book.search_all(search).distinct
    respond_to do |format|
      format.xlsx do
        response.headers["Content-Disposition"] =
          %(attachment; filename="books_#{search}.xlsx")
      end
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = t("admin.book.create_success")
      redirect_to admin_book_path(@book)
    else
      flash[:warning] = t("admin.book.create_fail")
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @book = Book.new
  end

  def update
    if @book.update(book_params)
      flash[:success] = t("admin.book.update_success")
      redirect_to admin_book_path(@book)
    else
      render :edit, status: :unprocessable_entity
      flash[:warning] = t("admin.book.update_fail")
    end
  end

  def show; end

  def edit
    @current_images = @book.images
  end

  def destroy
    if @book.destroy
      flash[:success] = t("admin.book.destroy_success")
    else
      flash[:warning] = t("admin.book.destroy_fail")
    end
    redirect_to admin_books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :published_year,
                                 :book_amount, :publisher_id, category_ids: [],
                                 author_ids: [],
                                 images_attributes: [:id, :image])
  end

  def find_book
    @book = Book.find_by id: params[:id]
    return if @book

    flash[:danger] = t("admin.book.not_found")
    redirect_to admin_books_path
  end

  def remove_images_before_update
    image_ids_to_remove = params[:remove_image_ids]
    return if image_ids_to_remove.blank?

    image_ids_to_remove.each do |image_id|
      image = @book.images.find_by(id: image_id)
      image.destroy if image.present?
    end
  end

  def set_books
    @books = Book.search_all(params[:search] || "").distinct
    session[:search] = params[:search]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i(show)
  def index
    @books = Book.search_all(params[:search] || "")
                 .distinct.paginate(page: params[:page],
                                    per_page: Settings.page.limit_items)
  end

  def show; end

  private
  def find_book
    @book = Book.find_by id: params[:id]
    return if @book

    flash[:danger] = t("book.wrong")
    redirect_to root_path
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td><%= book.title %></td>
  <td>
    <% if book.images.any? %>
      <%= image_tag book.images.first.image, alt: book.title, class: "book-image" %>
    <% else %>
      <%= t("admin.book.no_image") %>
    <% end %>
  </td>

  <td>
    <% book.categories.each do |category| %>
      <%= category.category_name %><br>
    <% end %>
  </td>
  <td><%= book.published_year %></td>
  <td><%= book.book_amount %></td>
  <td><%= book.publisher_name %></td>
  <td>
    <% book.authors.each do |author| %>
      <%= author.name %><br>
    <% end %>
  </td>
  <td>
    <% if book.average_rating.zero? %>
      <%= t("admin.book.no_review") %>
    <% else %>
      <%= book.average_rating %>
    <% end %>
  </td>
  <td>
    <%= link_to admin_book_path(book) do %>
      <i class="fas fa-eye "></i>
    <% end %>
    <span class="mx-2"></span>
    <%= link_to edit_admin_book_path(book) do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <span class="mx-2"></span>
    <%= link_to  admin_book_path(book), data: { "turbo-method": :delete,
                                           turbo_confirm: t("admin.delete") } do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: f.object  %>
  <div class="form-group">
    <%= f.label :title, t("admin.book.title") %>
    <span class="text-danger"><%= display_errors_for(@book, :title) %></span>
    <%= f.text_field :title, class: "form-control", placeholder: t("admin.book.title_holder") %>
  </div>

  <div class="form-group">
    <%= f.label :description, t("admin.book.description") %>
    <%= f.text_area :description, class: "form-control", placeholder: t("admin.book.description_holder") %>
  </div>

  <div class="form-group">
    <%= f.label :published_year, t("admin.book.published_year") %>
    <span class="text-danger"><%= display_errors_for(@book, :published_year) %></span>
    <%= f.number_field :published_year, class: "form-control", placeholder: t("admin.book.published_year_holder")%>
  </div>

  <div class="form-group">
    <%= f.label :book_amount, t("admin.book.book_amount") %>
    <span class="text-danger"><%= display_errors_for(@book, :book_amount) %></span>
    <%= f.number_field :book_amount, class: "form-control", placeholder: t("admin.book.book_amount_holder") %>
  </div>

  <div class="form-group">
    <%= f.label :publisher_id, t("admin.book.publisher_id") %>
    <span class="text-danger"><%= display_errors_for(@book, :publisher_id) %></span>
    <%= f.collection_select :publisher_id, Publisher.all, :id, :name, { prompt: t("admin.book.select_publisher") }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_ids, t("admin.book.categories") %>
    <span class="text-danger"><%= display_errors_for(@book, :category_ids) %></span>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :category_name do |cb| %>
      <div class="form-check">
        <%= cb.check_box %>
        <%= cb.label %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :author_ids, t("admin.book.authors") %>
    <span class="text-danger"><%= display_errors_for(@book, :author_ids) %></span>
    <%= f.collection_check_boxes :author_ids, Author.all, :id, :name do |cb| %>
      <div class="form-check">
        <%= cb.check_box %>
        <%= cb.label %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :images, t("admin.book.image") %>
    <% if @current_images.present? %>
      <div class="container">
        <div class="row">
          <% @current_images.each do |image| %>
            <div class="col-md-4">
              <%= image_tag url_for(image.image), alt: @book.title, class: "book-image" %>
              <div class="image-checkbox">
                <%= check_box_tag "remove_image_ids[]", image.id %>
                <%= label_tag "remove_image_ids_#{image.id}", t("admin.book.remove_image") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <p><%= t("admin.book.no_image") %></p>
    <% end %>
  </div>


  <div class="form-group">
      <%= f.label :images, t("admin.book.add_image") %>
      <% 5.times do |i| %>
        <%= f.fields_for :images, @book.images.build do |ff| %>
          <%= ff.file_field :image, class: "form-control", accept: "image/jpeg,image/gif,image/png"%>
          <br>
        <% end %>
      <% end %>
    </div>

  <div class="form-group">
    <%= f.submit t("admin.book.button"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<% provide(:title, t("admin.book.edit")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
    <h1 class="mt-4"><%= t("admin.book.edit")%></h1>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admin/books/index.html.erb
<% provide(:title, t("admin.header.book")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
        <h1 class="mt-4"><%= t("admin.header.book")%></h1>
        <div class="card mb-4">
          <div class="card-body text-center ">
            <%= link_to t("admin.book.new"),new_admin_book_path , class: "btn btn-primary" %>
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-header">
              <i class="fas fa-table me-1"></i>
              <%= t("admin.header.book")%> <%= t("admin.db") %>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-center align-items-center mt-4">
              <%= form_with url: admin_books_path, method: "get", class: "form-inline" do |form| %>
                <div class="input-group">
                  <%= form.text_field :search, id: "form1", class: "form-control-lg", placeholder: "Search" %>
                    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                      <i class="bi bi-search"></i>
                    <% end %>
                </div>
              <% end %>
            </div>
            <div class="search-box">
              </br>
              <%= form_tag admin_books_path, method: :get do %>
                <%= text_field_tag :book_search, params[:book_search], placeholder: t("admin.book.search_placeholder"), class: "form-control" %>
                </br>
                <%= submit_tag t("admin.book.search_button"), class: "btn btn-primary" %>
              <% end %>
            </div>
            <%= link_to t("admin.book.export"), export_excel_admin_books_path(format: :xlsx), class: "btn btn-primary mb-4" %>
            <table class="table table-bordered">
              <thead >
                <tr>
                  <th><%= t("admin.book.title") %></th>
                  <th><%= t("admin.book.image") %></th>
                  <th><%= t("admin.book.category") %></th>
                  <th><%= t("admin.book.published_year") %></th>
                  <th><%= t("admin.book.book_amount") %></th>
                  <th><%= t("admin.book.publisher_id") %></th>
                  <th><%= t("admin.book.authors") %></th>
                  <th><%= t("admin.book.average_rating") %></th>
                  <th><%= t("admin.book.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "book", collection: @books %>
              </tbody>
            </table>
          </div>
          <div class="d-flex justify-content-center align-items-center mt-5">
            <div class="digg_pagination">
                <%= will_paginate @books%>
            </div>
          </div>
        </div>
    </div>
  </main>
</div>

app/views/admin/books/new.html.erb
<% provide(:title, t("admin.book.new")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
    <h1 class="mt-4"><%= t("admin.book.new")%></h1>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admin/books/show.html.erb
<% provide(:title, t("admin.book.details")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4"><%= t("admin.book.details") %></h1>

      <div class="card mb-4">
        <div class="card-body">
          <h2><%= t("admin.book.info") %></h2>

          <dl class="row">
            <dt class="col-sm-3"><%= t("admin.book.title") %>:</dt>
            <dd class="col-sm-9"><%= @book.title %></dd>

            <dt class="col-sm-3"><%= t("admin.book.description") %>:</dt>
            <dd class="col-sm-9"><%= @book.description %></dd>

            <dt class="col-sm-3"><%= t("admin.book.average_rating") %>:</dt>
            <dd class="col-sm-9">
              <% if @book.average_rating.zero? %>
                <%= t("admin.book.no_review") %>
              <% else %>
                <%= @book.average_rating %>
              <% end %>
            </dd>

            <dt class="col-sm-3"><%= t("admin.book.publisher") %>:</dt>
            <dd class="col-sm-9"><%= @book.publisher_name %></dd>

            <dt class="col-sm-3"><%= t("admin.book.book_amount") %>:</dt>
            <dd class="col-sm-9"><%= @book.book_amount %></dd>

            <dt class="col-sm-3"><%= t("admin.book.published_year") %>:</dt>
            <dd class="col-sm-9"><%= @book.published_year %></dd>

            <dt class="col-sm-3"><%= t("admin.book.images") %>:</dt>
            <dd class="col-sm-9">
              <% if @book.images.any? %>
                <ul class="book-images">
                  <% @book.images.each do |image| %>
                      <%= image_tag url_for(image.image), alt: @book.title, class: "book-image" %>
                  <% end %>
                </ul>
              <% else %>
                <%= t("admin.book.no_image") %>
              <% end %>
            </dd>


            <dt class="col-sm-3"><%= t("admin.book.categories") %>:</dt>
            <dd class="col-sm-9">
              <ul>
                <% @book.categories.each do |category| %>
                 <%= category.category_name %>
                <% end %>
              </ul>
            </dd>


            <dt class="col-sm-3"><%= t("admin.book.author") %>:</dt>
            <dd class="col-sm-9">
              <ul>
                <% @book.authors.each do |author| %>
                 <%= author.name %>
                <% end %>
              </ul>
            </dd>

          </dl>

          <%= link_to t("admin.book.edit"), edit_admin_book_path(@book), class: "btn btn-primary" %>
          <%= link_to t("admin.book.back"), admin_books_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </main>
</div>