config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/static_pages/index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: :edit
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    delete "/logout", to: "sessions#destroy"

    resources :books, param: :id, only: %i(show new create) do
      resources :reviews
    end

    resources :users do
      resources :like_books, only: :index
      resources :transactions, only: %i(index show destroy)
    end

    resources :books do
      resources :like_books
      resources :transactions
    end

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages
      resources :books do
        collection do
          get :export_excel
        end
      end
      resources :authors
      resources :publishers
      resources :categories
      resources :users do
        member do
          post "active"
        end
      end
      resources :transactions
    end

    resources :authors do
      resources :follows, only: %i(create destroy)
    end

    resources :publishers, only: %i(show index) do
      resources :follows, only: %i(create destroy)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books_categories, dependent: :destroy
  has_many :books, through: :books_categories
  validates :category_name, presence: true, uniqueness: true,
                            length: {maximum: Settings.category.max}

  scope :filtered_by_name, lambda {|name|
    where("category_name LIKE ?", "%#{name}%") if name.present?
  }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :find_category, except: %i(index new create)
  def index
    @categories = Category.filtered_by_name(params[:category_search]).paginate(
      page: params[:page],
      per_page: Settings.per_page
    )
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = t("admin.category.create_success")
      redirect_to admin_categories_path
    else
      flash[:warning] = t("admin.category.create_fail")
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @category = Category.new
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = t("admin.category.update_success")
      redirect_to admin_categories_path
    else
      render :edit, status: :unprocessable_entity
      flash[:warning] = t("admin.category.update_fail")
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t("admin.category.destroy_success")
    else
      flash[:warning] = t("admin.category.destroy_fail")
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end

  def find_category
    @category = Category.find_by id: params[:id]
    return if @category

    flash[:danger] = t("admin.category.not_found")
    redirect_to admin_categories_path
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.category_name %></td>
  <td>
    <%= link_to edit_admin_category_path(category) do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <span class="mx-2"></span>

    <%= link_to  admin_category_path(category), data: { "turbo-method": :delete,
                                           turbo_confirm: t("admin.delete") } do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%=  form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object  %>
  <div class="form-group">
    <%= f.label :category_name, t("admin.category.name") %>
    <span class="text-danger"><%= display_errors_for(@category, :category_name) %></span>
    <%= f.text_field :category_name, class: "form-control", placeholder: t("admin.category.name_holder")  %>
  </div>

  <div class="form-group">
    <%= f.submit t("admin.book.button"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide(:title, t("admin.category.edit")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4"><%= t("admin.category.edit")%></h1>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, t("admin.header.category")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
        <h1 class="mt-4"><%= t("admin.header.category")%></h1>
        <div class="card mb-4">
          <div class="card-body text-center ">
            <%= link_to t("admin.category.new"), new_admin_category_path, class: "btn btn-primary" %>
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-header">
              <i class="fas fa-table me-1"></i>
              <%= t("admin.header.category")%> <%= t("admin.db") %>
          </div>
          <div class="card-body">
            <div class="search-box">
              <%= form_tag admin_categories_path, method: :get do %>
                <%= text_field_tag :category_search, params[:category_search], placeholder: t("admin.category.search_placeholder"), class: "form-control" %>
                </br>
                <%= submit_tag t("admin.category.search_button"), class: "btn btn-primary" %>
              <% end %>
            </div>
            <table class="table table-bordered">
              <thead >
                <tr>
                  <th><%= t("admin.category.name") %></th>
                  <th><%= t("admin.category.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "category", collection: @categories %>
              </tbody>
            </table>
          </div>
          <div class="d-flex justify-content-center align-items-center mt-5">
            <div class="digg_pagination">
                <%= will_paginate @categories%>
            </div>
          </div>
        </div>
    </div>
  </main>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, t("admin.category.new")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
      <h1 class="mt-4"><%= t("admin.category.new")%></h1>
      <div class="card mb-4">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/admin/categories/show.html.erb
<h1><%= t("admin.category.details") %></h1>
<p><strong><%= t("admin.category.name") %>:</strong> <%= @category.category_name %></p>