config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/static_pages/index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: :edit
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    delete "/logout", to: "sessions#destroy"

    resources :books, param: :id, only: %i(show new create) do
      resources :reviews
    end

    resources :users do
      resources :like_books, only: :index
      resources :transactions, only: %i(index show destroy)
    end

    resources :books do
      resources :like_books
      resources :transactions
    end

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages
      resources :books do
        collection do
          get :export_excel
        end
      end
      resources :authors
      resources :publishers
      resources :categories
      resources :users do
        member do
          post "active"
        end
      end
      resources :transactions
    end

    resources :authors do
      resources :follows, only: %i(create destroy)
    end

    resources :publishers, only: %i(show index) do
      resources :follows, only: %i(create destroy)
    end
  end
end

app/controllers/like_books_controller.rb
class LikeBooksController < ApplicationController
  before_action :logged_in_user
  before_action :load_book
  before_action :load_liked, only: :destroy
  def index
    @books = current_user.books.search_all(params[:search] || "")
                         .distinct.paginate(page: params[:page],
                                            per_page: Settings.page.limit_items)
  end

  def new
    @liked = UserLikeBook.new
  end

  def create
    @liked = current_user.user_like_books.new
    @liked.book_id = @book.id

    respond_to do |format|
      if @liked.save
        format.html{redirect_to @book}
        format.turbo_stream
      else
        flash[:danger] = t("like.like_fail")
      end
    end
  end

  def destroy
    respond_to do |format|
      if @liked.destroy
        format.html{redirect_to @book, status: :see_other}
        format.turbo_stream
      else
        flash[:danger] = t("like.unlike_fail")
      end
    end
  end

  private

  def load_book
    @book = Book.find_by id: params[:book_id]
  end

  def load_liked
    @liked = current_user.user_like_books.find_by book_id: params[:book_id]
  end
end

app/helpers/like_books_helper.rb
module LikeBooksHelper
  def like_message book
    count = book.user_like_books.count
    if current_user.books.exists?(book.id)
      if book.user_like_books.count > 1
        return t("like.you") + (count - 1).to_s +
               t("like.people")
      end
      t("like.only_you")
    else
      count.to_s + t("like.people")
    end
  end
end

app/views/like_books/_like.html.erb
<%= link_to book_like_books_path(@book), data: { "turbo-method": :post}, class: "like-button", id: "like", remote: true  do%>
  <%= render "shared/tym_icon"%>
<% end %>

app/views/like_books/_like_form.html.erb
<div class="d-flex flex-row bd-highlight mb-3">
  <div id="like_form">
  <% if current_user.books.exists?(@book.id) %>
    <%= render "like_books/unlike" %>
  <% else %>
    <%= render "like_books/like" %>
  <% end %>
  </div>
  <div id="like_message" class="mt-4 px-4">
    <%= like_message(@book) %>
  </div>
</div>

app/views/like_books/_unlike.html.erb
<%= link_to book_like_book_path(@book, current_user.books.find_by(id: @book.id)), data: { "turbo-method": :delete}, class: "unlike-button", id: "unlike", remote: true  do%>
  <%= render "shared/tym_icon"%>
<% end %>

app/views/like_books/create.turbo_stream.erb
<%= turbo_stream.update "like_form" do %>
  <%= render partial: "unlike" %>
<% end %>
<%= turbo_stream.update "like_message" do %>
  <%= like_message(@book) %>
<% end %>

app/views/like_books/destroy.turbo_stream.erb
<%= turbo_stream.update "like_form" do %>
  <%= render partial: "like" %>
<% end %>
<%= turbo_stream.update "like_message" do %>
  <%= like_message(@book) %>
<% end %>

app/views/like_books/index.html.erb
<h3><%= t("favorite_books")%></h3>
<div class="d-flex justify-content-center align-items-center mt-4">
  <%= form_with url: user_like_books_path(current_user), method: "get", class: "form-inline", autocomplete: "off"  do |form| %>
    <div class="input-group">
      <%= form.text_field :search, id: "form1", class: "form-control-lg", placeholder: "Search" %>
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="bi bi-search"></i>
        <% end %>
    </div>
  <% end %>
</div>
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">
    <div class="row gy-4 posts-list">
      <%= render "shared/show_book_item"%>
    </div>
  </div>
</section>