config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/static_pages/index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    resources :users
    resources :account_activations, only: :edit
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
    delete "/logout", to: "sessions#destroy"

    resources :books, param: :id, only: %i(show new create) do
      resources :reviews
    end

    resources :users do
      resources :like_books, only: :index
      resources :transactions, only: %i(index show destroy)
    end

    resources :books do
      resources :like_books
      resources :transactions
    end

    namespace :admin do
      root to: "static_pages#index"
      resources :static_pages
      resources :books do
        collection do
          get :export_excel
        end
      end
      resources :authors
      resources :publishers
      resources :categories
      resources :users do
        member do
          post "active"
        end
      end
      resources :transactions
    end

    resources :authors do
      resources :follows, only: %i(create destroy)
    end

    resources :publishers, only: %i(show index) do
      resources :follows, only: %i(create destroy)
    end
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::BaseController
  before_action :find_transaction, only: %i(update)

  def index
    @transactions = Transaction.order(updated_at: :desc)
                               .filter_by_status(params[:transaction_status])
                               .paginate(
                                 page: params[:page],
                                 per_page: Settings.authors.per_page
                               )
  end

  def update
    # Avoid callback trigger
    if @transaction.update_column(:status, transaction_params[:status])
      handle_when_update_success
    else
      handle_when_update_fail
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:status)
  end

  def find_transaction
    @transaction = Transaction.find_by(id: params[:id])
    return if @transaction

    flash[:danger] = t("book.wrong")
    redirect_to admin_transactions_path
  end

  def handle_when_update_success
    if @transaction.fail?
      new_book_amount = @transaction.amount.to_i + @transaction.book.book_amount
      @transaction.book.update_column(:book_amount, new_book_amount)
      TransactionMailer.deny_email(@transaction.user).deliver_now
    else
      TransactionMailer.accept_email(@transaction.user).deliver_now
    end

    redirect_when_success
  end

  def redirect_when_success
    flash[:success] =
      if @transaction.success?
        t("admin.transaction.actions.accepted")
      else
        t("admin.transaction.actions.denied")
      end
    redirect_to admin_transactions_path
  end

  def handle_when_update_fail
    flash.now[:danger] = t("book.wrong")
    redirect_to admin_transactions_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :logged_in_user
  before_action :find_book, only: %i(new create)
  before_action :find_user, only: %i(index destroy)
  before_action :find_transaction, only: %i(destroy)

  def index
    @transactions = @user.transactions
                         .filter_by_status(params[:transaction_status])
                         .order(updated_at: :desc)
                         .paginate(
                           page: params[:page],
                           per_page: Settings.authors.per_page
                         )
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = @book.transactions.build(transaction_params)
    if books_number_valid?
      @transaction.save ? handle_when_created_success : handle_when_created_fail
    else
      handle_when_created_fail
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      flash[:success] = t("transactions.destroy")
      format.html{redirect_to user_transactions_url(@user)}
    end
  end

  private

  def find_book
    @book = Book.find_by(id: params[:book_id])
    return if @book

    flash[:danger] = t("book.wrong")
    redirect_to root_path
  end

  def find_user
    @user = User.find_by(id: params[:user_id])
    return if @user

    flash[:danger] = t("book.wrong")
    redirect_to root_path
  end

  def handle_when_created_success
    flash[:success] = t("transactions.create.success")
    redirect_to book_path(@book)
  end

  def handle_when_created_fail
    flash.now[:danger] = t("transactions.create.fail")
    render :new, status: :unprocessable_entity
  end

  def books_number_valid?
    (@book.book_amount.to_i - @transaction.amount.to_i).positive?
  end

  def find_transaction
    @transaction = Transaction.find_by(id: params[:id])
    return if @transaction

    flash[:danger] = t("book.wrong")
    redirect_to root_path
  end

  def transaction_params
    params.require(:transaction).permit(:borrow_date, :expire_date, :amount,
                                        :user_id)
  end
end

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= transaction.id %></td>
  <td><%= transaction.user_name %></td>
  <td><%=link_to transaction.book_title, book_path(transaction.book) %></td>
  <td><%= transaction.borrow_date %></td>
  <td><%= transaction.expire_date %></td>
  <td><%= transaction.status %></td>
  <td><%= transaction.amount %></td>
  <td><%= transaction.updated_at %></td>
  <td>
  <% if transaction.pending? %>
    <%= link_to t("admin.transaction.select.cancel"), user_transaction_path(@user, transaction), data: { "turbo-method": :delete}, class: "btn btn-danger", remote: true %>
  <% end %>
  </td>
</tr>

app/views/transactions/index.html.erb
<% provide(:title, t("admin.header.transaction")) %>
<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid px-4">
        <h1 class="mt-4"><%= t("admin.header.transaction")%></h1>

        <div class="card mb-4">
          <h5 class="card-header">
            <%= t("admin.header.transaction")%> <%= t("admin.db") %>
          </h5>
          <div class="card-body">
            <div class="search-box">
              <%= form_tag user_transactions_path, method: :get do %>
                <div class="field">
                <%= label_tag :transaction_status %>
                <%= select_tag :transaction_status, options_for_select([[t("admin.transaction.select.pending"), t("admin.transaction.select.pending")], [t("admin.transaction.select.fail"), t("admin.transaction.select.fail")], [t("admin.transaction.select.success"), t("admin.transaction.select.success")], [t("admin.transaction.select.expire"), t("admin.transaction.select.expire")]], (params[:transaction_status] || t("admin.transaction.select.pending"))), class: "form-control" %>
                </div>
                <%= submit_tag t("admin.author.search_button"), class: "btn btn-primary" %>
              <% end %>
            </div>
            <table class="table table-bordered">
              <thead >
                <tr>
                  <th><%=t("admin.transaction.table.id")%></th>
                  <th><%=t("admin.transaction.table.username")%></th>
                  <th><%=t("admin.transaction.table.book_title")%></th>
                  <th><%=t("admin.transaction.table.requests_date")%></th>
                  <th><%=t("admin.transaction.table.expire_date")%></th>
                  <th><%=t("admin.transaction.table.status")%></th>
                  <th><%=t("admin.transaction.table.books_amount")%></th>
                  <th><%=t("admin.transaction.table.day_made")%></th>
                  <th><%=t("admin.transaction.table.actions")%></th>
                </tr>
              </thead>
              <tbody>
                <hr>
                <%= render @transactions %>
                <%= will_paginate renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
              </tbody>
            </table>
          </div>
        </div>
    </div>
  </main>
</div>

app/views/transactions/new.html.erb
<h1><%= t("transactions.new.create") %></h1>

<%= render "books/book_card" %>

<%= form_with(model: [@book, @transaction], local: true) do |form| %>
  <%= render "shared/object_error_messages", object: form.object %>

  <%= form.hidden_field :user_id, value: current_user&.id %>

  <div class="mb-3">
    <%= form.label :borrow_date, class: "form-label" %>
    <%= form.date_field :borrow_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :expire_date, class: "form-label" %>
    <%= form.date_field :expire_date, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", max: @book.book_amount %>
  </div>

  <%= form.submit t("transactions.new.create"), class: "btn btn-primary" %>
<% end %>